name: Actions from issue

on: issues

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: display
        if: |
          github.event.action == 'labeled' && contains(github.event.label.name, 'bug')
        run: echo 'run action!!'
