name: Actions from issue

on: issues

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: labeled
        if: |
         contains(github.event.label.name, 'bug') || contains(github.event.label.name, 'bug')
      - name: reopend
        if: |
          github.event.action == 'reopened' && contains(github.event.issue.labels.*.name, 'bug')
      - name: check
        if: |
          steps.labeled.conclusion == 'true' || steps.reopend.conclusion == 'true'
        run: echo 'run action!!'
