name: Actions from issue

on: issues

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: labeled
        if: |
         (github.event.label.name == 'bug' && contains(github.event.label.name, 'bug')) || (github.event.action == 'reopened' && contains(github.event.issue.labels.*.name, 'bug'))
        run: echo 'run action!!'
