name: Actions from issue

on: issues

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: display
        if: |
          contains(github.event.action, 'labeled') && contains(github.event.label.name, 'bug')
        run: echo 'run action!!'
