name: labels-actions
on:
  issues:
    types:
      ['labeled', 'unlabeled']

jobs:
  labeled-actions:
    runs-on: ubuntu-latest
    if: |
      (github.event.label.name == '対応中') || (github.event.label.name == '依頼中')
    name: Recording label's add or remove time
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: POST Comment
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          LABEL_NAME: ${{ github.event.label.name }}
          URL: ${{ github.event.issue.url }}
          TITLE: ${{ github.event.issue.title }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          data=$(cat <<EOF
          {
            "parent": { "database_id": "$DATABASE_ID" },
            "properties": {
              "Name": {
                "title": [
                  {
                    "text": {
                      "content": "TITLE"
                    }
                  }
                ]
              },
              "Tag": {
                "type": "number",
                "number": 600,
              },
            }
          }
          EOF
          )
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.MY_NOTION_TOKEN }}" \
            -H "Content-type: application/json" \
            -H "Notion-Version: 2021-05-13" \
            -d "$data" \
