name: labels-actions
on:
  issues:
    types:
      ['labeled', 'unlabeled']

jobs:
  labeled-actions:
    runs-on: ubuntu-latest
    if: |
      (github.event.label.name == '対応中') || (github.event.label.name == '依頼中')
    name: Recording label's add or remove time
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: POST Comment
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          URL: ${{ github.event.issue.url }}
          TITLE: ${{ github.event.issue.title }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\": \"Actions:シートに追加しました\"}" $URL
          curl -X POST -H "Content-Type: application/json" -d "{\"url\": \"$URL\", \"title\": \"$TITLE\"}" -L ${{ secrets.SPREAD_SHEET }}
