name: labels-actions
on:
  issues:
    types:
      ['labeled', 'unlabeled']

jobs:
  labeled-actions:
    runs-on: ubuntu-latest
    if: |
      (github.event.label.name == '対応中') || (github.event.label.name == '依頼中')
    name: Recording label's add or remove time
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: POST Comment
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          COMMENT_URL: ${{ github.event.issue.comments_url }}
          LABEL_NAME: ${{ github.event.label.name }}
          TITLE: ${{ github.event.issue.title }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\": \"ラベルが付きました\nラベル：　$LABEL_NAME\nタイトル：　$TITLE\"}" $COMMENT_URL
          data=$(cat <<EOF
          {
            "parent": { "database_id": "dfc2cdc260ae476c8f2f5d4065f9a94a" },
            "properties": {
              "Name": {
                "type": "title",
                "title": [{ "text": { "content": "POST Data" } }]
              },
              "Tags": {
                "type": "rich_text",
                "rich_text": [{ "text": { "content": "actions" } }]
              },
              "Price": {
                "type": "number",
                "number": 500
              },
              "Date": {
                "type": "date",
                "date": { "start": "2021-05-11" }
              },
              "Status": {
                "select": {
                  "name": "complete"
                }
              }
            }
          }
          EOF
          )
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.MY_NOTION_TOKEN }}" \
            -H "Content-type: application/json" \
            -H "Notion-Version: 2021-05-13" \
            -d "$data"
